name: example-environment
apt:
  packages:
    - libsm6
    - libxext6
    - ffmpeg
    - libfontconfig1
    - libxrender1
    - libgl1-mesa-glx
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - PyPortfolioOpt
    - ipywidgets
    - pandas
    - matplotlib
    - numpy
    - PyQt5
    - openpyxl
    - Cycler
    - opencv-python
    
