name: example-environment
channels:
  - conda-forge
dependencies:
  - libsm6
  - libxext6
  - ffmpeg
  - libfontconfig1
  - libxrender1
  - libgl1-mesa-glx
  - python
  - numpy
  - pip
  - pip:
    - PyPortfolioOpt
    - ipywidgets
    - pandas
    - matplotlib
    - numpy
    - PyQt5
    - openpyxl
    - Cycler
    - opencv-python
    
