name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - PyPortfolioOpt
    - ipywidgets
    - pandas
    - matplotlib
    - numpy
    - pyqt5
    - pyqt5-tools
    - openpyxl
    - Cycler
    - opencv-python
    
