name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - PyPortfolioOpt
    - ipywidgets
    - pandas
    - matplotlib
    - pypfopt
    - numpy
    
